monsite/monsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
path('question/', include('question.urls')), # add the proper path pattern
path('question2/', include('question2.urls')),
path('admin/', admin.site.urls),
]

monsite/question/urls.py
# -*- coding: utf-8 -*-
"""
Created on Wed Mar 31 17:57:54 2021

@author: mussa
"""

from django.urls import path
from . import views



app_name = 'question'

urlpatterns = [
path('', views.IndexView.as_view(), name='index'),
path('<int:pk>/', views.DetailView.as_view(), name='detail'),
path('<int:pk>/results/', views.ResultsView.as_view(),
name='results'),
path('<int:question_id>/vote/', views.vote, name='vote'),
]
               

monsite/question2/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

urlpatterns = [
path('', views.index, name='index'), #sets the path for the view
]

monsite/question/models.py
from django.db import models
from django.utils import timezone 
import datetime

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    question_id = models.IntegerField(default=0)
    
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text    
    
    def isAValidQuestion(self):
        if self.question.question_id >= 0 and isinstance(self.question.question_id, int):
            return True
        else:
            return False
        
    

monsite/question2/models.py
from django.db import models

# Create your models here.

monsite/question/views.py
from django.shortcuts import render
from django.http import Http404

# Create your views here.

from django.http import HttpResponse
from .models import Question
from django.template import loader
from django.http import HttpResponseRedirect
from .models import Choice
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

def get_queryset(self):
    #Excludes any questions that aren't published yet.
    return Question.objects.filter(pub_date__lte=timezone.now())


class IndexView(generic.ListView):
        template_name = 'question/index.html'
        context_object_name = 'latest_question_list'
        def get_queryset(self):
#Return the last five published questions.
            return Question.objects.order_by('-pub_date')[:5]
        
class DetailView(generic.DetailView):
    model = Question
    template_name = 'question/detail.html'
    
class ResultsView(generic.DetailView):
    model = Question
    template_name = 'question/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
# Redisplay the question voting form.
        return render(request, 'question/detail.html', {'question': question,'error_message': "You didn't select a choice.",})
    else:
        selected_choice.votes += 1
        selected_choice.save()
# Always return an HttpResponseRedirect after successfully dealing
# with POST data. This prevents data from being posted twice if a
# user hits the Back button.
        return HttpResponseRedirect(reverse('question:results', args=(question.id,)))

monsite/question2/views.py
from django.http import HttpResponse

def index(request):
    
    return HttpResponse("Hello, world. Comment ca va?")

monsite/question/templates/question/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'question:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

monsite/question/templates/question/index.html
{% if latest_question_list %}
<ul>
{% for question in latest_question_list %}
<li><a href="/question/{{ question.id }}/">{{ question.question_text }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>No question are available.</p>
{% endif %}

monsite/question/templates/question/results.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize
}}</li>
{% endfor %}
</ul>
<a href="{% url 'question:detail' question.id %}">Vote again?</a>